[package]
name = "cargo-xwin"
version = "0.8.3"
edition = "2018"
description = "Cross compile Cargo project to Windows MSVC target with ease"
license = "MIT"
keywords = ["windows", "cargo", "msvc"]
readme = "README.md"
repository = "https://github.com/messense/cargo-xwin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
cargo-options = "0.1.4"
clap = { version = "3.1.2", features = ["derive", "env", "wrap_help"] }
dirs = "4.0.0"
fs-err = "2.7.0"
indicatif = "0.17.0-rc.6"
path-slash = "0.1.4"
which = "4.2.4"
xwin = "0.2.0"
