[package]
name = "cargo-xwin"
version = "0.13.6"
edition = "2018"
description = "Cross compile Cargo project to Windows MSVC target with ease"
license = "MIT"
keywords = ["windows", "cargo", "msvc"]
readme = "README.md"
repository = "https://github.com/rust-cross/cargo-xwin"
rust-version = "1.62"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
cargo-config2 = "0.1.0"
cargo-options = "0.5.2"
clap = { version = "4.0.0", features = ["derive", "env", "wrap_help"] }
dirs = "4.0.0"
fs-err = "2.7.0"
indicatif = "0.17.2"
path-slash = "0.2.0"
which = "4.2.4"
xwin = { version = "0.2.9", default-features = false }

[features]
# By default we use rustls for TLS
default = ["rustls-tls"]
rustls-tls = ["xwin/rustls-tls"]
# If this feature is enabled we instead use the native TLS implementation for the
# target platform
native-tls = ["xwin/native-tls"]
